"""new_revision

Revision ID: 0804b5b6296b
Revises: c3577ca4551c
Create Date: 2025-04-11 10:31:10.394692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0804b5b6296b'
down_revision: Union[str, None] = 'c3577ca4551c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank', sa.Column('icon', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bank', 'icon')
    # ### end Alembic commands ###
