"""new_revision

Revision ID: 41818cc81052
Revises: 83b7496f381c
Create Date: 2025-03-22 21:10:09.998469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41818cc81052'
down_revision: Union[str, None] = '83b7496f381c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('commissionstep',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_type', sa.Enum('currency', 'individual_currency', native_enum=False), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('min', sa.Float(), nullable=False),
    sa.Column('max', sa.Float(), nullable=False),
    sa.Column('commission', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('individualcurrency',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('rate_source', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('currency', sa.Column('rate_source', sa.Text(), nullable=True))
    op.alter_column('currency', 'rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('currency', 'percent')
    op.drop_column('currency', 'min_amount')
    op.drop_column('currency', 'commission_step')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('commission_step', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('currency', sa.Column('min_amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('currency', sa.Column('percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('currency', 'rate',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('currency', 'rate_source')
    op.drop_table('individualcurrency')
    op.drop_table('commissionstep')
    # ### end Alembic commands ###
