"""new_revision

Revision ID: 60de03006a89
Revises: 0b24a3abd322
Create Date: 2025-03-06 08:45:11.566610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '60de03006a89'
down_revision: Union[str, None] = '0b24a3abd322'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activeapplication', 'amount', new_column_name="usdt_amount")
    op.drop_column('activeapplication', 'currency')
    op.alter_column('topup', 'amount', new_column_name="usdt_amount")
    op.drop_column('topup', 'amount_in_usd')
    op.alter_column('user_table', 'tether_balance', new_column_name="usdt_balance")
    op.alter_column('withdraw', 'amount_in_usd', new_column_name="usdt_amount")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('activeapplication', 'usdt_amount', new_column_name="amount")
    op.add_column('activeapplication', sa.Column('currency', sa.VARCHAR(length=6), autoincrement=False, nullable=False))
    op.alter_column('topup', 'usdt_amount', new_column_name="amount")
    op.add_column('topup', sa.Column('amount_in_usd', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('user_table', 'usdt_balance', new_column_name="tether_balance")
    op.alter_column('withdraw', 'usdt_amount', new_column_name="amount_in_usd")
    # ### end Alembic commands ###
