"""new_revision

Revision ID: 83b7496f381c
Revises: 60de03006a89
Create Date: 2025-03-22 14:54:22.628938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83b7496f381c'
down_revision: Union[str, None] = '60de03006a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('withdraw', sa.Column('document', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('withdraw', 'document')
    # ### end Alembic commands ###
