"""new_revision

Revision ID: c3577ca4551c
Revises: 41818cc81052
Create Date: 2025-03-22 21:31:58.840964

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3577ca4551c'
down_revision: Union[str, None] = '41818cc81052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('currency', sa.Column('min_amount', sa.Float(), nullable=False, server_default='0.0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('currency', 'min_amount')
    # ### end Alembic commands ###
